name: e-commerce-toolbox

services:
  rest-express:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:5000"

  postgres:
    image: postgres:18
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql
